### PR TITLE
Update navbar

### PR DESCRIPTION
**Pull request by t-lawan**
- Installed a carousel for the artist page.
- Added new CSS (Responsive Image, Text margins, etc)
- Updated navbar

### CODE REVIEW

**Comment by junekuhn** [comment]
We're not going to use a carousel, unfortunately it's bad UX practice https://shouldiuseacarousel.com/

**Comment by junekuhn** [comment]
everything else looks great though

**Review by junekuhn — CHANGES_REQUESTED** [review]
if we could just replace the carousel with a main static image for now, we can add the other images towards the bottom or something

**Comment by t-lawan** [comment]
Would the design team provide an update to the artist page?

If not, would we just render the images sequentially?

**Comment by junekuhn** [comment]
I sent you the video charlie made to change it on whatsapp.  What we can do is have all the images visible as clickable thumbnails, and the click swaps the picture in the header

**Comment by t-lawan** [comment]
Sweet, thanks. That looks cooler.

I'll update and let you know

**Comment by t-lawan** [comment]
This has been updated. I just put back the image.

**Pull request merged**
