### PR TITLE
Refactor pages to use templates

### PR DESCRIPTION
**Pull request by t-lawan**
- Created an SEO compoinent that takes in props
- Created base layout component to ensure code is not repeated. (Work needs to be done to exclude the layout from specific pages if required i.e. home page)
- Refacored and stripped current pages to use new layout component
- Created sketch for Ellipse test and imported to index page

### CODE REVIEW

**Comment by junekuhn** [comment]
__layout doesn't render because github pages doesn't accept underscores in static files.  I've created a template component in /lib that replaces the __layout.  This is the only workaround that I could think of

**Comment by t-lawan** [comment]
We may be able to add a .nojekyll file to the directory to solve this.

https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

**Comment by junekuhn** [comment]
ok yeah let's try that

**Comment by t-lawan** [comment]
Added it to this branch

**Pull request merged**
